module.exports = {
    OBTENER_USUARIOS: 1,
    CREAR_USUARIOS: 2,
    CREAR_CITAS: 4,
    EDITAR_CITAS: 5,
    CANCELAR_CITAS: 6,
    OBTENER_CITAS: 7,
    EDITAR_USUARIOS: 8,
    INACTIVAR_USUARIOS: 9,
    CREAR_PERFIL: 10,
    ASIGNAR_PERMISOS: 11,
    ACTIVAR_USUARIOS:12,
    ACTIVAR_CITAS:13

}

